name: WebSocket Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    strategy:
      matrix:
        include:
          - os: ubuntu
            version: 20.04
          - os: ubuntu
            version: 22.04
          - os: macos
            version: 13
          - os: macos
            version: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies on ubuntu
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get --reinstall install -y build-essential gcc cmake

      - name: Install dependencies on macos
        if: matrix.os == 'macos'
        run: |
          brew update
          brew reinstall gcc cmake

      #- name: Install Nix
      #  uses: DeterminateSystems/nix-installer-action@main
      #  with:
      #    github-token: ${{ secrets.GH_TOKEN }}

      - name: Build project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          make BUILD=debug -C examples/echoback

      - name: Run tests
        run: |
          cd tests && make test
