name: WebSocket Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    strategy:
      matrix:
        include:
          - os: ubuntu
            version: 20.04
          - os: ubuntu
            version: 22.04
          - os: macos
            version: 13
          - os: macos
            version: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies on ubuntu
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get --reinstall install -y build-essential gcc cmake

      - name: Install dependencies on macos
        if: matrix.os == 'macos'
        run: |
          brew update
          brew reinstall gcc cmake

      #- name: Apt update
      #  run: |
      #    wget -O - \
      #      https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
      #      gpg --dearmor - | \
      #      sudo tee /etc/apt/trusted.gpg.d/kitware.gpg > /dev/null
      #    sudo apt-add-repository -y \
      #      "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
      #    sudo apt update

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      # TODO: Switching to nixpkgs installation
      #- name: Install packages
      #  run: |
      #    : # Install packages
      #    sudo apt install -y \
      #      build-essential \
      #      gcc-9 \
      #      g++-9 \
      #      clang-tools \
      #      cmake
      #- name: Install packages
      #  run: |
      #    : # Install packages
      #    sudo apt install -y \
      #      build-essential \
      #      gcc-9 \
      #      g++-9 \
      #      clang-tools \
      #      cmake

      - name: Build project
        env:
          github-token: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir -p ~/.config/nix
          echo "access-tokens = github.com=${github-token}" >> ~/.config/nix/nix.conf
          make

      - name: Run tests
        run: |
          cd tests && make test
