name: WebSocket Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
#         - macos-13
#         - macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout google test
        uses: actions/checkout@v3
        with:
          repository: google/googletest

      - name: Install Nix
        run: |
          curl \
            --proto '=https' \
            --tlsv1.2 -sSf   \
            -L https://install.determinate.systems/nix | \
            sh -s -- install --no-confirm
          export PATH="${PATH}:/nix/var/nix/profiles/default/bin"

      # TODO: Switching to nixpkgs installation
      - name: Install packages
        run: |
          wget -O - \
            https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
            gpg --dearmor - | \
            sudo tee /etc/apt/trusted.gpg.d/kitware.gpg > /dev/null
          sudo apt-add-repository -y \
            "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
          sudo apt update
          : # Install packages
          sudo apt install \
            gcc-9 \
            g++-9 \
            clang-tools \
            cmake
          : # Install google test
          cd googletest && \
            mkdir build && \
            cd build && \
            cmake .. -DBUILD_GMOCK=OFF -DGOOGLETEST_VERSION=1.13.0 && \
            make && \
            make install

      #- name: Install Dependencies
      #  run: |
      #    nix-env -iA nixpkgs.llvmPackages_19.clang-tools
      #    nix-env -iA nixpkgs.gccgo14
      #    nix-env -iA nixpkgs.gtest

      - name: Build project
        run: |
          make

      - name: Run tests
        run: |
          make test
